### ISSUE TITLE
Release 1.1.0 images.

### ISSUE THREAD

**Issue by mach6** [paypal/docker-selion#11]
With the SeLion 1.1.0 release available, we should tag and release corresponding docker images from this project..
- release tag `1.1.0`
- release tag `latest` pointing to `1.1.0`
- update `develop` tag to a current build which is based on the current SeLion `develop` branch

**Comment by mach6** [comment]
@sebady fyi. Are we waiting for the current PR's to merge first?

**Comment by sebady** [comment]
Yes the existing PR should merge before 1.1.0.
