### ISSUE TITLE
Containers would exit unexpectedly due to IndexOutOfBoundsException error

### ISSUE THREAD

**Issue by aovsiyenko** [paypal/docker-selion#13]
QA at Control Mobile implemented SeLion automation framework to run tests against Web app.
We are using Docker images of SeLion hub and Firefox/Chrome drivers.

There were several cases there containers exited unexpectedly.
I examined log and found following error (more details in attached file):
[chromedriver container log.txt](https://github.com/paypal/docker-selion/files/1166898/chromedriver.container.log.txt)

Exception in thread "SeLionJarSpawnerShutdownHook" java.lang.IndexOutOfBoundsException: Index: -1, Size: 7
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)

Thank you, Alex

![image](https://user-images.githubusercontent.com/10671895/28484967-c17d6aac-6e2a-11e7-8034-58327b2a6ec3.png)

**Comment by mach6** [comment]
By default we configure the `docker-selion/hub` to trigger a shutdown request of a `docker-selion` node after 50 unique sessions (per node) -- https://github.com/paypal/docker-selion/blob/develop/hub/Dockerfile.txt#L15

You can alter this behavior by sending `-e SELGRID_UNIQUE_SESSION_COUNT={someval}`with the docker command that starts the `docker-selion/hub` process. To disable it send the value `-1` -- https://github.com/paypal/SeLion/blob/develop/server/src/main/java/com/paypal/selion/proxy/SeLionRemoteProxy.java#L67-L80

**Comment by mach6** [comment]
@aovsiyenko closing this. comment back if you have further questions on the topic
